"""Add parent_id and casdoor_org_id to tenants

Revision ID: 685454eafcaa
Revises: 03ea244985ce
Create Date: 2025-12-18 16:37:10.364039

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '685454eafcaa'
down_revision = '03ea244985ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casdoor_organization_mappings',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('casdoor_org_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='casdoor_organization_mapping_pkey'),
    sa.UniqueConstraint('casdoor_org_id', name='unique_casdoor_org_id'),
    sa.UniqueConstraint('tenant_id', name='unique_tenant_id')
    )
    with op.batch_alter_table('app_triggers', schema=None) as batch_op:
        batch_op.alter_column('provider_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('quota_used',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', models.types.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('casdoor_org_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('casdoor_org_id')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('quota_used',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('app_triggers', schema=None) as batch_op:
        batch_op.alter_column('provider_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    op.drop_table('casdoor_organization_mappings')
    # ### end Alembic commands ###
